### PR TITLE
Add #1. Add unicode in hanjpuncode.h

### PR DESCRIPTION
**Pull request by Ohgu**
Add unicode of every consonants, vowels for choseong, jungseong, jongseong and sort in the ascending way.

### CODE REVIEW

**Review by JSYoo5B — APPROVED** [review]
LGTM

By the way, is this necessary?
@onting , how about your opinion?

**Comment by onting** [comment]
It can be used in anthor implementation of automata. @JSYoo5B 
@Ohgu I think it's better to skip writing coutinueos values to keep it simple.

**Comment by Ohgu** [comment]
@onting I think you're right. I'll delete continuous values and PR again.

**Comment by JSYoo5B** [comment]
I have opposite opinion.
I think specifying unicode value will clarify the value of constants.
Also, adding comment about which character may improve readability between korean pronounciasion into roman writing

Ex.

**Review by onting — APPROVED** [review]
Lgtm

**Comment by onting** [comment]
I think the specifying isn't necessary because we don't have to know the values in programming.
We'd just prefer to use declared enums in that time.
However, I also think commenting in hangul improve readability.
@JSYoo5B

**Pull request merged**
