### PR TITLE
bugfix: resolve segfault on glib usage

### LINKED ISSUE #23: [BUG] Segmentation fault occurs when it destruct InputContext
Currently, we have an memory issue for preedit string in InputContext object.
I'm testing library code using below
```
#include "hanjpinputcontext.h"

int main()
{
    int i;
    HanjpInputContext *context;
    GArray *preedit;
    GArray *committed;
    GArray *hangul;
    gchar *res;

    const char *s = "gkwlapaktlxp.";

    context = hanjp_ic_new();
    preedit = hanjp_ic_ref_preedit_string(context);
    committed = hanjp_ic_ref_commit_string(context);
    hangul = hanjp_ic_ref_hangul_string(context);
    for(i = 0; s[i]; i++) {
        hanjp_ic_process(context, s[i]);
    }
    res = g_ucs4_to_utf8((const gunichar*)committed->data, committed->len, NULL, NULL, NULL);
    g_object_unref(context);
    return 0;
}
```
This code pushs string representing "하지메마시테." to InputContext.
I suggest you to write test program like above and link libhanjp for test, and run it on GDB.
For this, you should add program building code to CMakeLists.txt like below
```
...
add_exectutable(test_suit test.c)
target_link_libraries(test_suit hanjp)
...
```
VS Code UI is convenient for variable inspection.

This issue is related in preedit string manipulation code, so you should check ic_process, am_push, and ic_dispose.

### PR DESCRIPTION
**Pull request by JSYoo5B**
Resolves #23

### CODE REVIEW

**Comment by JSYoo5B** [comment]
Even patched with commit 711a1701b665110ba5744245252903627fb0aa11, segfault are still invoked. (from other function call)

```
(process:409272): GLib-CRITICAL **: 16:47:11.146: g_atomic_ref_count_dec: assertion 'g_atomic_int_get (arc) > 0' failed

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7f8ad01 in g_type_check_instance () from /lib/x86_64-linux-gnu/libgobject-2.0.so.0
(gdb) bt
#0  0x00007ffff7f8ad01 in g_type_check_instance () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#1  0x00007ffff7f7f73a in g_signal_handlers_destroy () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#2  0x00007ffff7f67311 in  () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#3  0x0000555555556a63 in hanjp_ic_dispose (self=0x55555556f870)
    at /home/jsyoo5b/Workspace/hanjp/libhanjp/hanjpinputcontext.c:46
#4  0x00007ffff7f67c93 in g_object_unref () at /lib/x86_64-linux-gnu/libgobject-2.0.so.0
#5  0x0000555555556658 in main () at /home/jsyoo5b/Workspace/hanjp/libhanjp/test.c:22
```

**Comment by JSYoo5B** [comment]
The previous commit 711a1701b665110ba5744245252903627fb0aa11 called wrong argument passing.

Signature of function [`g_array_unref()`](https://docs.gtk.org/glib/type_func.Array.unref.html) is `(GArray*)`.
But, the previous commit passed argument as `&priv->preedit`, which is `(GArray**)`

This mistake was caused by the signature difference between [`g_clear_object()`](https://docs.gtk.org/gobject/func.clear_object.html) and [`g_object_unref()`](https://docs.gtk.org/gobject/method.Object.unref.html)

**Review by onting — APPROVED** [review]
Oh good, I thought any object derived from GObject could be deallocated by g_object_dispose and g_object_fininalize because it is overrided by deriving type and chained up for parent types.
However, your fix shows some types in (even) GLib must be deallocated its own dedicated funcation.
It is big discovery, thank you for PR.

**Comment by onting** [comment]
Or are (even) some types in GLib are not derived from GObject?
It seems like that.

**Comment by JSYoo5B** [comment]
@onting When you search for [`g_*_unref`](https://docs.gtk.org/glib/index.html?q=unref) in GLib documentation, You can see that all GLib-implemented data types has own unreference functions.

> Oh good, I thought any object derived from GObject type could be deallocated by g_object_dispose and g_object_fininalize because it is overrided by deriving type and chained up for parent types.

I also thought same as you, But it seems that GLib-implemented data structures have their own struct inside.

Following structs have visible members in header: (which can directly get/set members to change state)

* [GArray and its relevant data structures](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/garray.h#L36-57)
* [GList](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/glist.h#L37-44)

In contrast, there are other structs which members are not visible: (which cannot see which members are in the struct)

* [GHashTable](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/glist.h#L37-44)
* [GAsyncQueue](https://gitlab.gnome.org/GNOME/glib/-/blob/main/glib/gasyncqueue.c#L95-103)

I guess these GLib implemented objects are not relevant with GObject.

1. The purpose of GObject is to provide Object-Oriented characteristics in C language.
2. The user(programmer who uses GObject) can define and link methods(signal functions) to their defined struct. (as a class)
3. By the characteristics of the Object-Oriented, classes(objects) should be converted into other objects (maybe by inheritance?)
4. But, the data structures in GLib, their requirements are obvious. (ex. init, deinit, get, set, insert, append, remove, index, etc)
5. So, the contributers of GLib may thought that it doesn't need GObject. (those data structures are unnecessary to get expanded)

**Comment by onting** [comment]
It makes sense. I agree with you.

**Pull request merged**
