### PR TITLE
Migrate to GObject from C++

### PR DESCRIPTION
**Pull request by onting**
We've rewritten our library code on GObject because 
1. It's difficult to write new engine type on C++
2. GObject can generate glue code automatically
3. GObject have dynamic type register(for custom automata)

The design is very similar to old C++ code, however, there are some difference and you should see two main entry point for them.
We have two main entry point: InputContext(hanjpinputcontext.h) and Automata(hanjpautomata.h).
For kana string producer which takes ASCII code, you should use InputContext.
For kana string producer without keyboard mapping(it takes hangul jaso), you should use Automata.
And changes are
For InputContext:
1. Custom automata selecting functions are added.
2. process return type is changed to int from enum(FAIL if negative, POP if positive, EAT if 0)
3. Implemented missing functions

For Automata:
1. Exposed HanjpBuffer
2. You should pass buffer to to_kana function(and it changes buffer value)

And there are some extra code changes:
1. Change CMake checks
2. Changed to fetch libhangul from upstream and load it directly from source code.
3. Write install rules
4. Write test suites

### CODE REVIEW

**Comment by JSYoo5B** [comment]
it'd be good to add `CHANGELOG` or something else.
Otherwise, tagging & add descriptions into Release would be fine as well.

**Review by JSYoo5B — APPROVED** [review]

**Comment by JSYoo5B** [comment]
This PR resolves #13. (and other containing PRs which had been merged into `develop`)

**Comment by onting** [comment]
It seems good to write changes on tag

**Comment by onting** [comment]
> This PR resolves #13. (and other containing PRs which had been merged into `develop`)

Oh, It slipped in my mind, thanks

**Pull request merged**
