### PR TITLE
feat[Automata]: Implement backspace method

### PR DESCRIPTION
**Pull request by JSYoo5B**
* Implement ambase backspace() method
  Based on cpp reference code

* Cannot figure out how to register amdefault's `backspace()` method call into ambase's `backspace()` method

### CODE REVIEW

**Review by onting — CHANGES_REQUESTED** [review]
Looks good,
But I think it's better to write as
``` 
...

else {
   return FALSE;
}

return TRUE;
```
Rather then store and returning, it's more clear what we are returning at the statements.

**Comment by JSYoo5B** [comment]
@onting Ok. I'll change this into early return.

And is there any reference or recommendation about inheritance method linking problem?

**Review by onting — APPROVED** [review]
LGTM

**Comment by onting** [comment]
For inheritance problem...
Yes, currently, the code for AutomataDefault wouldn't overrided, whereas the code for AutomataBase does.
I'll handle for this inheritance issue.
But if you want to understand inheritance in libhanjp, I recommand you to read followings.
[Interface](https://developer-old.gnome.org/gobject/stable/howto-interface.html#howto-interface-define)
[methods](https://developer-old.gnome.org/gobject/stable/howto-gobject-methods.html)

**Comment by onting** [comment]
Approximately,
In class_init function, we can override member functions.
In interface init funtion, we implements Interface(in libhanjp, we implements Automata interface by AutomataBase class).

**Pull request merged**
